#!/usr/bin/env bash
set -eu
(set -o pipefail) 2>/dev/null && set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

LOG_DIR="${LOG_DIR:-${PROJECT_ROOT}/logs}"
mkdir -p "${LOG_DIR}"

STEP2_SCRIPT="${PROJECT_ROOT}/runfiles/02_prepare_ptq_standard.sh"
RUN_TAG="${RUN_TAG:-$(date +%Y%m%d_%H%M%S_%N)}"
LOG_FILE="${LOG_DIR}/step2_prepare_ptq_${RUN_TAG}.log"
GPU_COUNT="${GPU_COUNT:-}"
CUDA_DEVICES="${CUDA_DEVICES:-}"
RESUME="${RESUME:-1}"
KEEP_BLOCKS="${KEEP_BLOCKS:-}"
ACT_QUANT_MODE="${ACT_QUANT_MODE:-lookup}"
WEIGHT_GROUP_SIZE="${WEIGHT_GROUP_SIZE:-64}"
TIMESTEP_COUNT="${TIMESTEP_COUNT:-40}"
SMOOTHQUANT_ENABLE="${SMOOTHQUANT_ENABLE:-0}"
SMOOTHQUANT_ALPHA="${SMOOTHQUANT_ALPHA:-0.8}"
SMOOTHQUANT_EPS="${SMOOTHQUANT_EPS:-1e-5}"
ROTATION_ENABLE="${ROTATION_ENABLE:-0}"
ROTATION_PATH="${ROTATION_PATH:-}"
ROTATION_SEED="${ROTATION_SEED:-17}"

nohup env \
RUN_TAG="${RUN_TAG}" \
GPU_COUNT="${GPU_COUNT}" \
CUDA_DEVICES="${CUDA_DEVICES}" \
RESUME="${RESUME}" \
KEEP_BLOCKS="${KEEP_BLOCKS}" \
ACT_QUANT_MODE="${ACT_QUANT_MODE}" \
WEIGHT_GROUP_SIZE="${WEIGHT_GROUP_SIZE}" \
TIMESTEP_COUNT="${TIMESTEP_COUNT}" \
SMOOTHQUANT_ENABLE="${SMOOTHQUANT_ENABLE}" \
SMOOTHQUANT_ALPHA="${SMOOTHQUANT_ALPHA}" \
SMOOTHQUANT_EPS="${SMOOTHQUANT_EPS}" \
ROTATION_ENABLE="${ROTATION_ENABLE}" \
ROTATION_PATH="${ROTATION_PATH}" \
ROTATION_SEED="${ROTATION_SEED}" \
bash "${STEP2_SCRIPT}" \
  > "${LOG_FILE}" 2>&1 &

echo "[RUNNING] step2_prepare_ptq pid=$!"
echo "[LOG] ${LOG_FILE}"
echo "[TIP] device mode: GPU_COUNT=${GPU_COUNT} CUDA_DEVICES=${CUDA_DEVICES}"
echo "[TIP] resume mode: RESUME=${RESUME} (1=skip if prepared.pt already exists)"
echo "[TIP] quant config: ACT_QUANT_MODE=${ACT_QUANT_MODE} KEEP_BLOCKS=${KEEP_BLOCKS:-<none>} WEIGHT_GROUP_SIZE=${WEIGHT_GROUP_SIZE}(compat-only) TIMESTEP_COUNT=${TIMESTEP_COUNT}"
echo "[TIP] smoothquant: SMOOTHQUANT_ENABLE=${SMOOTHQUANT_ENABLE} SMOOTHQUANT_ALPHA=${SMOOTHQUANT_ALPHA} SMOOTHQUANT_EPS=${SMOOTHQUANT_EPS}"
echo "[TIP] rotation: ROTATION_ENABLE=${ROTATION_ENABLE} ROTATION_SEED=${ROTATION_SEED} ROTATION_PATH=${ROTATION_PATH:-<internal deterministic>}"
echo "[TIP] if you changed SQ/rotation settings, run with RESUME=0 to rebuild prepared.pt"
echo "[TIP] stage2 log: ${PROJECT_ROOT}/logs/prepare_ptq_latest.log"
